### ISSUE TITLE
Extension is broken (and removed from Chrome store)

### ISSUE THREAD

**Issue by tomhundt** [tanmayrajani/Download-Quora-Answers#1]
Sadly, this appears to be broken at this point (3/23/20).  Last update was 2018 -- it had a good run!  I'm guessing Quora changed something in their html/css. 
 (The line with the upvotes and datestamp looks different now, and of course no `Download` appears.) 

Possibly (probably?) related, Google seems to have pulled it from their extension store.  Not sure if that alone is enough to disable it.

**Comment by tanmayrajani** [comment]
> Google seems to have pulled it from their extension store

Yes, I got an email a while back from Quora (lawyers?) that they've got the extension taken down. I guess this is it. :cry: 

![image](https://user-images.githubusercontent.com/8295888/77389598-a1d9bc00-6db9-11ea-8188-6bd38ec5b644.png)
